### ISSUE TITLE
InvalidSmilesException should be public

### ISSUE THREAD

**Issue by dan2097** [johnmay/beam#5]
Graph.fromSmiles throws the checked exception InvalidSmilesException, but this class is package protected which complicates catching it. Probably InvalidSmilesException should be public.
An alternative fix would be to declare Graph.fromSmiles as throwing an IOException as InvalidSmilesException extends from this.

**Comment by johnmay** [comment]
You should catch the IOException... https://github.com/cdk/cdk/blob/master/storage/smiles/src/main/java/org/openscience/cdk/smiles/SmilesParser.java#L261. I probably should have thrown that instead but since v2.0 will be out any year now I'm not going to change it since it's workable.
