### ISSUE TITLE
Is "C0CCCCC%0" a valid SMILES?

### ISSUE THREAD

**Issue by mohacsizs** [johnmay/beam#7]
https://github.com/johnmay/beam/blob/335ee67bfe886613cd0ed27ae89a98150c46af13/core/src/test/java/uk/ac/ebi/beam/OpenSMILESSpecificationTest.java#L261

Is "C0CCCCC%0" a correct SMILES string? I think it should be "C0CCCCC%00" or "C%00CCCCC%00".

Quote from the [OpenSMILES Specification](http://opensmiles.org/spec/open-smiles-3-input.html#3.4):

> Two-digit ring numbers are permitted, but must be preceeded by the percent "%" symbol, such as "C%25CCCCC%25" for cyclohexane. Three-digit numbers and larger are never permitted. However, note that three digits are not invalid; for example, "C%123" is the same as "C3%12", that is, an atom with two rnum specifications.
> 
> The digit(s) representing a ring-closure are interpreted as a number, not a symbol, and two rnums match if their numbers match. Thus, C1CCCCC%01 is a valid SMILES and is the same as C1CCCCC1. Likewise, C%00CCCCC%00 is a valid SMILES.

**Comment by johnmay** [comment]
I allow single digit ring closures on '%', Beam v2.0 issues a warning. Mainly because I did find an example out in the wild.
