### ISSUE TITLE
Missing git tag for release v1.3.3

### ISSUE THREAD

**Issue by merkys** [johnmay/beam#8]
This repository seems to lack git tags for some of the releases, for example, the most recent one, v1.3.3. Could you please add it?

**Comment by johnmay** [comment]
Done

**Comment by merkys** [comment]
Thanks a lot @johnmay!

**Comment by johnmay** [comment]
Thanks for reporting. I do have a Beam 2.0 rewrite coming out soon so this repo is in a bit of limo at the moment. Hence why I forgot to tag the patch releases.
